/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WorkRouteRouteImport } from './routes/work/route'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSalmagenRouteImport } from './routes/work/salmagen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRouteRoute = WorkRouteRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRouteRoute,
} as any)
const WorkSalmagenRoute = WorkSalmagenRouteImport.update({
  id: '/salmagen',
  path: '/salmagen',
  getParentRoute: () => WorkRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work': typeof WorkRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/salmagen': typeof WorkSalmagenRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/salmagen': typeof WorkSalmagenRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work': typeof WorkRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/salmagen': typeof WorkSalmagenRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work' | '/sitemap.xml' | '/work/salmagen' | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/work/salmagen' | '/work'
  id: '__root__' | '/' | '/work' | '/sitemap.xml' | '/work/salmagen' | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkRouteRoute: typeof WorkRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRouteRoute
    }
    '/work/salmagen': {
      id: '/work/salmagen'
      path: '/salmagen'
      fullPath: '/work/salmagen'
      preLoaderRoute: typeof WorkSalmagenRouteImport
      parentRoute: typeof WorkRouteRoute
    }
  }
}

interface WorkRouteRouteChildren {
  WorkSalmagenRoute: typeof WorkSalmagenRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteRouteChildren: WorkRouteRouteChildren = {
  WorkSalmagenRoute: WorkSalmagenRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteRouteWithChildren = WorkRouteRoute._addFileChildren(
  WorkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkRouteRoute: WorkRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
